spring:
  datasource:
    url: jdbc:oracle:@oracle.fiap.com.br:1521:ORCL
    username: RM98641
    password: 280504
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
